name: Shapefile Check

on:
  pull_request:
    branches:
      - main  # Or the name of your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install geopandas

      - name: Run shapefile comparison script
        run: python compare_shapefiles.py https://github.com/LL-Geo/check_geojson/blob/main/re.geojson https://github.com/LL-Geo/check_geojson/blob/main/re.geojson

      - name: Post difference as comment
        run: |
          DIFFERENCE=$(cat difference.txt)
          PAYLOAD=$(echo '{}' | jq --arg body "$DIFFERENCE" '.body = $body')
          COMMENTS_URL=$(jq -r .pull_request.comments_url "$GITHUB_EVENT_PATH")
          curl -s -S -H "Authorization: token ${{ Token_S }}" --header "Content-Type: application/json" --data "$PAYLOAD" "$COMMENTS_URL"
